package com.bjtu.bean;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.book_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.amount
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_id
     *
     * @return the value of cart.user_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_id
     *
     * @param userId the value for cart.user_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.book_id
     *
     * @return the value of cart.book_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.book_id
     *
     * @param bookId the value for cart.book_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.amount
     *
     * @return the value of cart.amount
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.amount
     *
     * @param amount the value for cart.amount
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}