package com.bjtu.bean;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.order_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.user_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.creat_date
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private Date creatDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_order.total_price
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private BigDecimal totalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.order_id
     *
     * @return the value of user_order.order_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.order_id
     *
     * @param orderId the value for user_order.order_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.user_id
     *
     * @return the value of user_order.user_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.user_id
     *
     * @param userId the value for user_order.user_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.creat_date
     *
     * @return the value of user_order.creat_date
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.creat_date
     *
     * @param creatDate the value for user_order.creat_date
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_order.total_price
     *
     * @return the value of user_order.total_price
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_order.total_price
     *
     * @param totalPrice the value for user_order.total_price
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }
}