package com.bjtu.bean;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.book_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.amount
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.order_id
     *
     * @return the value of order_item.order_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.order_id
     *
     * @param orderId the value for order_item.order_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.book_id
     *
     * @return the value of order_item.book_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.book_id
     *
     * @param bookId the value for order_item.book_id
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.amount
     *
     * @return the value of order_item.amount
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.amount
     *
     * @param amount the value for order_item.amount
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}