package com.bjtu.dao;

import com.bjtu.bean.Cart;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("bookId") Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    Cart selectByPrimaryKey(@Param("userId") Integer userId, @Param("bookId") Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    int updateByPrimaryKey(Cart record);
}