package com.bjtu.dao;

import com.bjtu.bean.OrderItem;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    int deleteByPrimaryKey(@Param("orderId") Integer orderId, @Param("bookId") Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    OrderItem selectByPrimaryKey(@Param("orderId") Integer orderId, @Param("bookId") Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    List<OrderItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    int updateByPrimaryKey(OrderItem record);
}