package com.bjtu.dao;

import com.bjtu.bean.Order;
import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    Order selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_order
     *
     * @mbg.generated Fri Apr 16 18:18:31 CST 2021
     */
    int updateByPrimaryKey(Order record);
}